#PARA EJECUTAR ESTE COMPOSE SE TIENE QUE CREAR LAS IMAGENES DEL ECOMMERCE, TANTO BACK COMO FRONT
#docker build . -t ec_bk
#docker build . -t ec_fn

services:
  pa_db:
    container_name: pa_db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: pa_db
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql #los datos de mysql se guardan en la carpta "db"
    restart: on-failure
    networks:
      red_pa:
        ipv4_address: 192.168.56.100

  ec_bk:
    container_name: ec_bk
    image: ec_bk:latest
    ports:
      - "8090:8080"
    networks:
      red_pa:
        ipv4_address: 192.168.56.101
    depends_on:
      pa_db:
        condition: service_started
    restart: on-failure

  ec_fn:
    container_name: ec_fn
    image: ec_fn:latest
    ports:
      - "5173:5173"
    networks:
      red_pa:
        ipv4_address: 192.168.56.102
    depends_on:
      ec_bk:
        condition: service_started
    restart: on-failure

networks:
  red_pa:
    name: red_pa
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.56.0/24

volumes:
  db_data:
