spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${DB_NAME:pa_db}?createDatabaseIfNotExist=true
    username: ${DB_ROOT_USER:Aldana}
    password: ${DB_ROOT_PASSWORD:12345}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    banner-mode: off
