spring:
  datasource:
    # url: jdbc:mysql://localhost:3306/${DB_NAME:pa_db}?createDatabaseIfNotExist=true
    # username: ${DB_ROOT_USER:root}
    # password: ${DB_ROOT_PASSWORD:admin}
    # driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  main:
    banner-mode: off
  mail:
    host: smtp.gmail.com
    port: 587
    username: ecommerceCrupiers@gmail.com
    password: wmll tkvu lzho pima
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true